export const COURSES_TO_NAMES: Record<string, string> = {
	ARABIC101R: "Introduction to Arabic 1",
	ASL101R: "American Sign Language 1",
	BET100: "Foundations of Entrepreneurial Practice",
	BET320: "Entrepreneurial Strategy",
	BET430: "Sales Fundamentals",
	BET460: "Business Negotiations",
	BIOL150: "Organismal and Evolutionary Ecology",
	BIOL239: "Genetics",
	CLAS101: "Classical and Contemporary Cultures",
	CLAS104: "Classical Mythology",
	CLAS202: "Love, Life, and Death in Rome",
	CO250: "Introduction to Optimization",
	CO353: "Computational Discrete Optimization",
	CO456: "Introduction to Game Theory",
	CS452: "Real-Time Programming",
	CS466: "Algorithm Design and Analysis",
	CS488: "Introduction to Computer Graphics",
	CS492: "The Social Implications of Computing",
	EARTH122: "Introductory Environmental Sciences",
	EARTH281: "Geological Impacts on Human Health",
	ECE305: "Introduction to Quantum Mechanics",
	ECE457A: "Co-operative and Adaptive Algorithms",
	ECON101: "Introduction to Microeconomics",
	ECON212: "Introduction to Game Theory",
	ENGL101B: "Introduction to Rhetorical Studies",
	ENGL108B: "Global English Literatures",
	ENGL108P: "Popular Potter",
	ENGL306A: "Introduction to Linguistics",
	FINE150: "Appreciation and Expression",
	JAPAN101R: "First-Year Japanese 1",
	MATH235: "Linear Algebra 2 for Honours Mathematics",
	MUSIC140: "Popular Music and Culture",
	MUSIC246: "Soundtracks: Music in Film",
	MUSIC275: "Music and Technology",
	PHIL208: "Philosophy Through Science Fiction",
	PSYCH101: "Introductory Psychology",
	PSYCH207: "Cognitive Processes",
	SCI238: "Introductory Astronomy",
	SFM101: "Introduction to Sustainability and Financial Management",
	SPCOM223: "Public Speaking",
	CHE102: "Chemistry for Engineers",
	CS240: "Data Structures and Data Management",
	CS241: "Foundations of Sequential Programs",
	CS241e: "Foundations of Sequential Programs (Enriched)",
	CS247: "Software Engineering Principles",
	CS341: "Algorithms",
	CS343: "Concurrent and Parallel Programming",
	CS349: "User Interfaces",
	MATH119: "Calculus 2 for Engineering",
	MATH135: "Algebra for Honours Mathematics",
	MATH239: "Introduction to Combinatorics",
	SE101: "Introduction to Methods of Software Engineering",
	SE212: "Logic and Computation",
	SE350: "Operating Systems",
	SE380: "Introduction to Feedback Control",
	SE464: "Software Design and Architectures",
	SE491: "Design Project 2",
	STAT206: "Statistics for Software Engineering",
	ECE106: "Electricity and Magnetism",
	CS138: "Introduction to Data Abstraction and Implementation",
	CS348: "Introduction to Database Management",
	MATH115: "Linear Algebra for Engineering",
	ECE192: "Engineering Economics and Impact on Society",
	ECE105: "Classical Mechanics",
	ECE222: "Digital Computers",
	MATH213: "Signals, Systems, and Differential Equations",
	ECE124: "Digital Circuits and Systems",
	ECE140: "Linear Circuits",
	SE463: "Software Requirements Specification and Analysis",
	CS137: "Programming Principles",
	SE465: "Software Testing and Quality Assurance",
	SE490: "Design Project 1",
	CS370: "Numerical Computation",
	CS451: "Data-Intensive Distributed Computing",
	CO487: "Applied Cryptography",
	SYDE548: "User Centred Design Methods",
	CS449: "Human-Computer Interaction",
	ECE459: "Programming for Performance",
	SE390: "Design Project Planning",
	GENE403: "Interdisciplinary Design Project 1",
	GENE404: "Interdisciplinary Design Project 2",
	MATH117: "Calculus 1 for Engineering",
	CS484: "Computational Vision",
	CS479: "Neural Networks",
	CS493: "Team Project 1",
	CS494: "Team Project 2",
};

type terms = "1A" | "1B" | "2A" | "2B" | "3A" | "3B" | "4A" | "4B";

export const TERMS_TO_CORE_COURSES: Record<terms, string[]> = {
	"1A": ["MATH135", "SE101", "MATH115", "MATH117", "ECE105", "CS137"],
	"1B": ["MATH119", "ECE106", "ECE124", "ECE140", "SE102", "CS138"],
	"2A": ["CHE102", "CS241", "CS241e", "SE212", "STAT206", "SE201", "ECE222"],
	"2B": ["CS240", "CS247", "CS348", "MATH239", "SE202", "ECE192"],
	"3A": ["MATH213", "CS341", "CS349", "SE350", "SE301"],
	"3B": ["ECE358", "CS343", "SE380", "SE464", "SE390", "SE302"],
	"4A": ["SE463", "SE490", "SE401"],
	"4B": ["SE491", "SE402"],
};
