/**
 * List of questions for fun
 */
export const SURVEY_ONE_QUESTIONS = [
	"What year were you born?",
	"What racial or ethnic groups describe you?",
	"Are you an out-of-province student?",
	"Are you an international student?",
	"Are you multilingual?",
	"What languages do you speak?",
	"What languages do you speak at home?",
	"Where is your family's home located?",
	"How many siblings do you have?",
	"Are you the eldest, youngest, or in the middle?",
	"Have any of them also studied at Waterloo?",
	"What is the highest level of education of your parents?",
	"How many hackathons did you attend in high school?",
	"First programming language?",
	"Did you attend CEGEP?",
	"If you attended CEGEP, what program did you attend?",
	"Did you have any job experience relevant to SE prior to starting 1A?",
	"What other job experience did you have prior to starting 1A?",
	"What other universities did you apply to?",
	"Out of all of the university programs you applied to, how would you rank Waterloo SE?",
	"Which extracurriculars were you part of in high school?",
	"How many years of programming experience did you have prior to starting 1A?",
	"Did you participate in any high school enrichment programs?",
	"How many people did you know from high school that also went to Waterloo?",
	"Did you take a gap year between high school and university?",
	"If you took a gap year, why did you choose to take one?",
	"What was your high school adjustment factor?",
	"What was your high school admissions average?",
	"Did you play any sports in high school?",
	"Have you ever considered dropping out?",
	"Have you ever considered switching out of SE? If so, to which program/school?",
	"If you had to start again, what school/program would you enrol in?",
	"Did you do any options as part of your degree?",
	"Did you do any specializations as part of your degree?",
	"Did you minor in anything as part of your degree?",
	"Did you train in a sport competitively during your undergrad?",
	"On average, when do you go to sleep?",
	"Did you go on exchange?",
	"Which term did you go on exchange?",
	"Which university did you go to on exchange?",
	"How high was your workload during exchange?",
	"How stressed were you during exchange?",
	"Favourite part of going on exchange?",
	"Hardest thing about going on exchange?",
	"Most valuable thing you took away from exchange?",
	"Stream 8 vs 8x vs 8y",
	"What language do you use for programming interviews?",
	"Have you ever been late to a co-op interview?",
	"Have you ever missed a co-op interview?",
	"Any fun interview stories?",
	"How did you find your co-op?",
	"What was your co-op role?",
	"What company did you work at?",
	"How many employees worked at your company?",
	"Which industry was your co-op employer in?",
	"What was your hourly co-op salary?",
	"What programming languages did you use at your co-op?",
	"Where was your co-op?",
	"What would you rate your co-op experience?",
	"Favourite overall co-op city?",
	"Anything else co-op related you'd like to add?",
	"Favourite colour (as a hex code)?",
	"What social media/messaging apps do you use?",
	"Favourite Emoji?",
	"What pets do you have?",
	"Which OS do you use for schoolwork?",
	"What is your daily browser?",
	"Anything else you'd like to add?",
] as const;

export const SURVEY_TWO_QUESTIONS = [
	"How many volunteer hours did you complete in high school?",
	"Why did you choose Waterloo SE?",
	"What is your gender?",
	"What was your parents' total income at the time that you were admitted into university?",
	"How many roommates did you have in each school term? [1A]",
	"How many roommates did you have in each school term? [1B]",
	"How many roommates did you have in each school term? [2A]",
	"How many roommates did you have in each school term? [2B]",
	"How many roommates did you have in each school term? [3A]",
	"How many roommates did you have in each school term? [3B]",
	"How many roommates did you have in each school term? [4A]",
	"How many roommates did you have in each school term? [4B]",
	"Where did you live during your school terms?",
	"If you have taken an academic course during a co-op term, when?",
	"If you have taken an academic course during a co-op term, why?",
	"If you have overloaded a term, when?",
	"If you have overloaded, which course(s) did you overload, and did you complete the course(s)?",
	"What device do you most frequently use to take notes?",
	"What note-taking software do you use?",
	"Which List 1 ATE did you take?",
	"Opinions on List 1 ATEs",
	"Which List 2 ATE did you take?",
	"Opinions on List 2 ATEs",
	"Which List 3 ATE did you take?",
	"Opinions on List 3 ATEs",
	"Favourite core course?",
	"Least favourite core course?",
	"Most useful core course?",
	"Least useful core course?",
	"Favourite core course professor?",
	"Favourite elective course (no ATEs), and why?",
	"Easiest study term?",
	"Hardest study term?",
	"Do you plan on getting your P. Eng?",
	"Which school term did you spend the most time working on your FYDP?",
	"How much did you enjoy working on your FYDP?",
	"What category is your FYDP?",
	"Did you transfer into SE from another program?",
	"What was your term average in 1A?",
	"What is your cumulative average?",
	"Anything else you'd like to add about academics? (courses, FYDP, etc.)",
	"What technical extracurriculars did you actively participate in?",
	"What non-technical extracurriculars did you actively participate in?",
	"Are there any extracurriculars you regret not joining? Why?",
	"Which intramurals did you participate in?",
	"Which terms did you participate in intramurals?",
	"How many technical side projects did you complete during university?",
	"How many hackathons did you attend in university? [1A]",
	"How many hackathons did you attend in university? [1B]",
	"How many hackathons did you attend in university? [2A]",
	"How many hackathons did you attend in university? [2B]",
	"How many hackathons did you attend in university? [3A]",
	"How many hackathons did you attend in university? [3B]",
	"How many hackathons did you attend in university? [4A]",
	"How many hackathons did you attend in university? [4B]",
	"How often do you go out/party on average?",
	"How many hours of sleep do you get on average?",
	"How many meals do you cook per week on average during school terms?",
	"How many times do you go out to eat per week on average during school terms?",
	"Have you ever had a co-op term without a placement?",
	"How many co-op offers did you have rescinded?",
	"Have you ever been banned from WaterlooWorks for reneging an offer/match?",
	"Have you ever gotten COVID?",
	"How many times have you gotten COVID?",
	"Have you ever experienced long COVID symptoms?",
	"How often did you exercise during your undergrad?",
	"What types of exercise did you do during your undergrad?",
	"If you experienced burnout during SE, what factors contributed?",
	"How is your self-esteem now compared to before starting university?",
	"In first year?",
	"In 4B?",
	"How many times did you ask for a deadline extension due to illness/injury?",
	"How many times did you need to visit the ER during your undergrad?",
	"How often do you keep in touch with high school friends?",
	"How many people in SE25 have you ever met and spoken to in-person?",
	"How many close friends do you have that you first met in high school?",
	"How many close friends do you have that you first met through co-op?",
	"How many close friends do you have that you first met on campus residence?",
	"How many close friends do you have that you first met through being part of the SE25 cohort (i.e. by taking the same core courses or attending cohort events)?",
	"How many close friends do you have that you first met through being part of SE (other cohorts)?",
	"How many close friends do you have that you first met in extracurriculars (e.g. clubs, sports)?",
	"How many close friends do you have that you first met through other means (e.g. parties, Aphrodite project, mutual friends)",
	"Have you been contacted by the CRA for tax-related reasons?",
	"Have you ever intentionally committed tax fraud?",
	"What is your current net worth?",
	"What percentage of your net worth is invested?",
	"How much did you borrow in student loans throughout university?",
	"How satisfied are you about your current financial situation?",
	"What are your post graduation plans?",
	"How many grad school offers have you received so far?",
	"Which school?",
	"What is your research topic or program?",
	"Why did you choose to pursue grad school over full-time employment?",
	"How many full-time offers have you received so far?",
	"If you have accepted an offer, which company?",
	"How large is the company that extended your full-time offer (number of employees)?",
	"Which industry is the company that extended your full-time offer in?",
	"When are you starting full-time work?",
	"How many days per week do you plan to work remotely?",
	"Are you returning to a previous co-op?",
	"If you are returning to a previous co-op, when did you work for that company?",
	"What is your total first-year compensation?",
	"What is your annual base salary?",
	"What is your one-time sign-on bonus?",
	"What is the value of your first-year stock grant?",
	"What is your total stock grant value?",
	"What is your end-of-year/recurring annual compensation?",
	"How content are you with your post-grad plans?",
	"What city will you be living in full-time after graduation?",
	"What were the 3 most important motivators in your full-time decision?  [Compensation]",
	"What were the 3 most important motivators in your full-time decision?  [Proximity to Friends]",
	"What were the 3 most important motivators in your full-time decision?  [Proximity to Family]",
	"What were the 3 most important motivators in your full-time decision?  [Proximity to Significant Other]",
	"What were the 3 most important motivators in your full-time decision?  [City choice]",
	"What were the 3 most important motivators in your full-time decision?  [Cost of Living]",
	"What were the 3 most important motivators in your full-time decision?  [Interest in Work]",
	"What were the 3 most important motivators in your full-time decision?  [Interest in Team]",
	"What were the 3 most important motivators in your full-time decision?  [Interest in Product]",
	"What were the 3 most important motivators in your full-time decision?  [Company Fit (WLB, Culture)]",
	"What were the 3 most important motivators in your full-time decision?  [Remote Work]",
	"What were the 3 most important motivators in your full-time decision?  [In-Person Work]",
	"What were the 3 most important motivators in your full-time decision?  [Vibes]",
	"Are you left-handed, right-handed, or ambidextrous?",
	"Favourite SE25-related memory?",
	"What countries did you travel to during your degree?",
	"Favourite study spot?",
	"What grocery store did you most frequently shop at?",
] as const;

export const SURVEY_THREE_QUESTIONS = [
	"What is your religious and/or spiritual affiliation?",
	"What is your sexual orientation?",
	"How many classes did you fail?",
	"If you failed a class, which class did you fail?",
	"How many midterms did you fail?",
	"How many finals did you fail?",
	"Have you ever been arrested?",
	"What counselling resources did you use during your undergrad?",
	"Have you ever been to therapy?",
	"How many school terms were you affected by struggles associated with mental health?",
	"What mental health issues have you faced? [Anxiety]",
	"What mental health issues have you faced? [Body Dysmorphia]",
	"What mental health issues have you faced? [Burnout]",
	"What mental health issues have you faced? [Depression]",
	"What mental health issues have you faced? [Eating Disorders]",
	"What mental health issues have you faced? [Grief]",
	"What mental health issues have you faced? [OCD]",
	"What mental health issues have you faced? [Neurodivergence (ADHD, Autism, etc.)]",
	"What mental health issues have you faced? [Post-traumatic Stress Disorder (PTSD) / Complex post-traumatic Stress Disorder (CPTSD)]",
	"What mental health issues have you faced? [Social Anxiety Disorder]",
	"What mental health issues have you faced? [None]",
	"What mental health issues have you faced? [PMDD]",
	"What mental health issues have you faced? [Body-Focused Repetitive Behaviour]",
	"Which drugs have you used? [Alcohol]",
	"Which drugs have you used? [Caffeine]",
	"Which drugs have you used? [Nicotine and Tobacco]",
	"Which drugs have you used? [Weed (THC)]",
	"Which drugs have you used? [Adderall/Ritalin (unprescribed)]",
	"Which drugs have you used? [Mushrooms]",
	"Which drugs have you used? [LSD]",
	"Which drugs have you used? [Cocaine]",
	"Drank alcohol, taken an edible, or done another drug in class?",
	"Written a final drunk, hungover, high or on another drug?",
	"How many romantic relationships have you been in during your degree?",
	"How many months of your degree have you spent in a romantic relationship?",
	"What dating apps did you use while in university?",
	"Did you ever participate in the Aphrodite project?",
	"Which relationship/intimacy actions have you performed? [Held hands romantically]",
	"Which relationship/intimacy actions have you performed? [Been on a date]",
	"Which relationship/intimacy actions have you performed? [Kissed someone romantically]",
	"Which relationship/intimacy actions have you performed? [Been in a committed relationship]",
	"Which relationship/intimacy actions have you performed? [Been in a long-distance relationship]",
	"Which relationship/intimacy actions have you performed? [Been in a situationship]",
	"Which relationship/intimacy actions have you performed? [Sent/received nudes]",
	"Which relationship/intimacy actions have you performed? [Engaged in sexual intercourse]",
	"Which relationship/intimacy actions have you performed? [Hooked up with someone]",
	"Which relationship/intimacy actions have you performed? [Had a threesome]",
	"Have you been involved in romantic cheating during your degree?",
	"How many sexual partners did you have during your degree?",
	"Have you ever done a naughty act in the SE Lounge/Labs?",
	"Rice purity test score?",
	"What was your rice purity test before university?",
	"What is your iron ring size?",
	"If you received an iron ring, have you lost your iron ring as of doing this survey?",
	"Have you ever physically fought someone outside of controlled martial arts environments (with intent to cause physical harm)?",
	"Do you use tabs or spaces when indenting your code?",
	"Where do you put your function brackets?",
	"Favourite programming language?",
	"Favourite text editor or IDE?",
	"Do you capitalize letters while typing with Caps Lock or Shift?",
	"Do you use your chosen IDE in light or dark mode?",
	"Which phone OS do you use?",
	"How many Leetcode Easy problems have you solved?",
	"How many Leetcode Medium problems have you solved?",
	"How many Leetcode Hard problems have you solved?",
	"What video games did you frequently play during your degree?",
	"How many hours did you play video games per week during your degree?",
	"How many hours did you spend on social media platforms per week during your degree?",
	"Favourite boba shop around UW?",
	"Favourite restaurant in Waterloo?",
	"Favourite shawarma restaurant around UW?",
	"Favourite inspirational quote/words to live by?",
	"Best life hack/tip?",
	"Advice you'd give your first-year self?",
] as const;

export const SECEST_QUESTIONS = [
	"Did you ever commit SEcest with another SE25?",
	"Did you at any point want to commit SEcest with an SE25?",
	"What terms did you commit SEcest with another SE25?",
] as const;

export const SWITCH_OUT_QUESTIONS = [
	"Which term did you switch out of SE25?",
	"Why did you choose to switch out of SE25?",
	"Which program did you switch to?",
	"Is there anything else you'd like to add?",
] as const;

/**
 * Questions that we map, but don't include in the question or section lists for some reason
 */
export const IDK_ABOUT_THESE_ONES_CHIEF = [
	// Missing in Question Mappings
	"1A",
	"1B",
	"2A",
	"2B",
	"3A",
	"3B",
	"4A",
	"4B",

	// Missing in Questions to Sections
	"Anything else you’d like to add?",
	"Any feedback on this survey?",
	"(Second co-op term) Which industry was your co-op employer in?",
	"Have you ever unintentionally committed tax fraud?",
	"Anything else to add about full-time?",
	"How useful did you find your List 3 ATE?",
	"Why did you think this course was useful?",
	"Why did you think this course wasn't useful?",
	"Will you continue working on your FYDP after symposium?",
	"What was your term average in 1B?",
	"What was your term average in 2A?",
	"What was your term average in 2B?",
	"What was your term average in 3A?",
	"What was your term average in 3B?",
	"What was your term average in 4A?",
	"What was your term average in 4B?",
	"How many meals do you cook per week on average during co-op terms?",
	"How many times do you go out to eat per week on average during co-op terms?",
] as const;

/**
 * Questions (titles) for graphs/sections using multiple survey questions
 */
export const GROUPED_QUESTIONS = [
	// Grouped bar graphs
	"How many roommates did you have in each school term?",
	"Which drugs have you used?",
	"Which relationship/intimacy actions have you performed?",
	"How many hackathons did you attend in university?",
	"What were the 3 most important motivators in your full-time decision?",

	// Box plots
	"What was your term average?",
	"How many Leetcode problems have you solved?",
	// "How many times do you cook/go out to eat per week?",
	"During co-op terms?",
	"During school terms?",

	// Other
	"What mental health issues have you faced?",

	"Average Hourly Co-op Salary vs Gender",
	// "Average Hourly Co-op Salary vs Family Income",
	"First-year Total Compensation vs Gender",
	"First-year Total Compensation vs Grades",
	"First-year Total Compensation vs Family Income",
	"Co-op Regions - Flow over Terms",
] as const;

export type SURVEY_QUESTION =
	| (typeof SURVEY_ONE_QUESTIONS)[number]
	| (typeof SURVEY_TWO_QUESTIONS)[number]
	| (typeof SURVEY_THREE_QUESTIONS)[number]
	| (typeof SECEST_QUESTIONS)[number]
	| (typeof SWITCH_OUT_QUESTIONS)[number]
	| (typeof IDK_ABOUT_THESE_ONES_CHIEF)[number]
	| (typeof GROUPED_QUESTIONS)[number];
